### ISSUE TITLE
Fallback language not working?

### ISSUE THREAD

**Issue by jaimeagudo** [i18next/react-i18next#318]
Not sure wether this is a bug or a misconfiguration, just testing the given example for _nextjs_ (https://github.com/i18next/react-i18next/tree/master/example/nextjs) I got this stack trace on the browser when I set the browser locale to `es` which is a missing locale.

```
cannot read property 'home' of undefined
TypeError: Cannot read property 'home' of undefined
    at /Users/me/react-i18next/example/nextjs/.next/dist/i18n.js:51:72
    at Array.forEach (native)
    at /Users/me/react-i18next/example/nextjs/.next/dist/i18n.js:50:16
    at Array.forEach (native)
    at I18n.i18n.getInitialProps (/Users/me/react-i18next/example/nextjs/.next/dist/i18n.js:48:22)
    at _callee$ (/Users/me/react-i18next/example/nextjs/.next/dist/pages/index.js:98:61)
    at tryCatch (/Users/me/react-i18next/example/nextjs/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/me/react-i18next/example/nextjs/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/me/react-i18next/example/nextjs/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/me/react-i18next/example/nextjs/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)

```

I tried adding   `fallbackLng: true` at https://github.com/i18next/react-i18next/blob/master/example/nextjs/server.js#L19 but it made no difference

Am I missing something? Many thanks

**Comment by jamuhl** [comment]
just pushed an update: https://github.com/i18next/react-i18next/commit/5fb85bc75f9e0c8f102df97a1b51c6609c20ebb1

should be fixed with that change

**Comment by jaimeagudo** [comment]
aha, this is first class support level mate! 👍 😄 Tested and working! Many thanks for the super fast patch!

**Comment by jamuhl** [comment]
you're welcome...

just spread the word ;), start the repo and if going to need a translation management have a look at our solution https://locize.com (same level of support)
