### ISSUE TITLE
Works fine on Web/Desktop, fails on Mobile.

### ISSUE THREAD

**Issue by SkyzohKey** [i18next/react-i18next#396]
Hey guys, I'm currently working on a project that is platfom-agnostic (react-native-web) with my own components and stuff, and I'd like to add i18next to the project. So it works fine on the web/desktop builds (react) but when it comes to mobile (react-native), the following error happens in Metro:

```js
error: bundling failed: Error: While trying to resolve module `react-i18next` from file `/home/skyzohkey/Dev/React/Tox-Universal-Client/App.js`, the package `/home/skyzohkey/Dev/React/Tox-Universal-Client/node_modules/react-i18next/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/home/skyzohkey/Dev/React/Tox-Universal-Client/node_modules/react-i18next/dist/commonjs/index.js`. Indeed, none of these files exist:

  * `/home/skyzohkey/Dev/React/Tox-Universal-Client/node_modules/react-i18next/dist/commonjs/index.js(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
  * `/home/skyzohkey/Dev/React/Tox-Universal-Client/node_modules/react-i18next/dist/commonjs/index.js/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
    at ResolutionRequest.resolveDependency (/home/skyzohkey/Dev/React/Tox-Universal-Client/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:104:15)
    at DependencyGraph.resolveDependency (/home/skyzohkey/Dev/React/Tox-Universal-Client/node_modules/metro/src/node-haste/DependencyGraph.js:271:4465)
    at dependencies.map.relativePath (/home/skyzohkey/Dev/React/Tox-Universal-Client/node_modules/metro/src/DeltaBundler/traverseDependencies.js:379:19)
    at Array.map (<anonymous>)
    at resolveDependencies (/home/skyzohkey/Dev/React/Tox-Universal-Client/node_modules/metro/src/DeltaBundler/traverseDependencies.js:378:16)
    at /home/skyzohkey/Dev/React/Tox-Universal-Client/node_modules/metro/src/DeltaBundler/traverseDependencies.js:203:33
    at Generator.next (<anonymous>)
    at step (/home/skyzohkey/Dev/React/Tox-Universal-Client/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:307)
    at /home/skyzohkey/Dev/React/Tox-Universal-Client/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:467
    at <anonymous>
 BUNDLE  [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/4), failed.

```

You can try yourself to reproduce by cloning my repository here: https://github.com/Tox-Client/client/

Thanks in advance guys, I've tried all I can do before opening that issue and I hope you will be better than me at finding the issue c:

**Comment by jamuhl** [comment]
honestly no idea...

**Comment by SkyzohKey** [comment]
Fact is that the file actually is present but Métro does not seems to be able to read it. Maybe a permissions issue? /:

**Comment by jamuhl** [comment]
idk...you might need to ask over at metro?!?

**Comment by jamuhl** [comment]
any update on this?

**Comment by SkyzohKey** [comment]
Yeah that was a stupid issue caused by my electron-builder config + rn-cli.config.js blacklist XD. Fixed !
